---
# Conteudo utilizado com foco nos estudo do curso AWX e Ansible para Sys Admin ministrado por Phillipe Farias
# As técnicas utilizadas podem não ser as mais eficientes para realização das tarefas, apenas foram utilizadas para concluir os desafios do curso.
# https://www.udemy.com/course/awx-para-sysadmin/?srsltid=AfmBOooEBvdfG8wD0r-1PmE8XsO0dBaiytCWFAL0i3vM3ElVe1ys4hhx
# https://www.udemy.com/course/ansible-para-sysadmin/?srsltid=AfmBOor4kNTXtSrTkUAWFtOlVSWtMFUhb66H_w1AdLXMftSoXn_OySU_

- name: Add New User
  hosts: all
  tasks:
    - name: User | Add User
      user:
        name: "{{ username }}"
        comment: "{{ comment }}"
        shell: "{{ shell }}"
        home: "{{ home }}"
        password: "{{ '{{ password }}' | password_hash('sha512', 'mysecretsalt') }}"

...