download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/amazon-aws-9.4.0.tar.gz
format_version: 1.0.0
name: aws
namespace: amazon
server: https://galaxy.ansible.com/api/
signatures: []
version: 9.4.0
version_url: /api/v3/plugin/ansible/content/published/collections/index/amazon/aws/versions/9.4.0/
